### ISSUE TITLE
【Conductor】__conductor_workflowdir__の削除機能で配下のフォルダが削除できない

### ISSUE THREAD

**Issue by sh-myoga** [exastro-suite/exastro-it-automation#2725]
### バグの説明
__conductor_workflowdir__の配下にフォルダを作成した場合、削除機能で該当のフォルダを削除できない

### 再現方法
__conductor_workflowdir__の配下にフォルダを作成するPlaybookを実行する。

```yaml
- name: FILE Copy
  ansible.builtin.copy:
    src: "{{ CPF_testfileA }}"
    dest: /tmp/testfileA

- name: FILE Fetch
  ansible.builtin.fetch:
    src: /tmp/testfileA
    dest: "{{ __conductor_workflowdir__ }}/testfile"
```

### 本来期待する挙動
配下のフォルダも含めて削除できること
